apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  containers:
  - name: web-server
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-data
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["rm", "/homework/index.html"]
    command: ["/bin/bash", "-c"]
    args:
    - |
      cat > /etc/nginx/conf.d/default.conf <<EOF
      server {
        listen 8000;
        server_name localhost;
        location / {
          root /homework;
          index index.html;
        }
      }
      EOF
      nginx -g "daemon off;"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  initContainers:
  - name: init-html
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "<html><body><h1>Hello For Otus from Kubernetes!</h1></body></html>" > /init/index.html
    volumeMounts:
    - name: shared-data
      mountPath: /init
  volumes:
  - name: shared-data
    emptyDir: {}